version: '3'

services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - '6379:6379'
  pgadmin:
    image: dpage/pgadmin4:5.6
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=root
  postgres:
    image: postgres:13.3
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=typeorm
